### ISSUE TITLE
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

### ISSUE THREAD

**Issue by Wei-Gao-CAS** [simonhmartin/twisst#11] opened 2020-04-15 02:25 UTC
Dear Simon,

 

I'm using your software twisst. But I got a problem which I can't handle. I hope you can help me. Thanks a lot. 

 

Here is my scripts and erro information. And you can find the input files in attachment.

 

command line:

/gpfs/home/gaowei/anaconda2/envs/anaconda3/bin/python3 /gpfs/home/gaowei/00.biosoft/twisst-master/twisst.py -t test.tree  -w res.test.output.weights.csv.gz --outputTopos res.test.topologies.trees -g NJ -g GHP -g GHV -g AKS --groupsFile group.AKS.txt --outgroup NJ -D res.test.dists.txt

 

erro infor:

Traceback (most recent call last):
  File "/gpfs/home/gaowei/00.biosoft/twisst-master/twisst.py", line 626, in 
    simplify=not args.skip_simplify, abortCutoff=args.abortCutoff, verbose=args.verbose)
  File "/gpfs/home/gaowei/00.biosoft/twisst-master/twisst.py", line 404, in weightTree
    currentDists[taxPair[0],taxPair[1]] = currentDists[taxPair[1],taxPair[0]] = sum(leafLeafChains[comboPair[0]][comboPair[1]].dists)
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by simonhmartin** [comment] 2020-04-15 09:38
I'm not sure what the problem might be, but it appears to be related to computation of pairwise distances. For now I recommend removing the -D option from your command, until I can find the bug.

**Comment by simonhmartin** [comment] 2020-05-06 13:26
This was caused by a bug in the code to retrieve pairwise distances (-D option). The bug should be fixed in the latest version of twisst.py.

**Closed by simonhmartin** 2020-05-06 13:26 UTC
